dist: trusty
sudo: true
addons:
  chrome: stable
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/module-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
language: groovy
jdk:
- openjdk7
services:
- mysql
script:
- ./grailsw test-app :unit --non-interactive
before_install:
- echo "Before Install"
- chmod +x travis-build.sh
- mysql -e 'CREATE DATABASE IF NOT EXISTS linkshare';
after_install:
- echo "After Install"
before_script:
- echo "Before Script"
- rm -rf target
after_script:
- echo "After Script"
#deploy:
#- provider: s3
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#  local_dir: dpl_cd_upload
#  skip_cleanup: true
#  on:
#    branch: master
#  bucket: abhilash-nexthoughts
#  region: "us-east-2"
#- provider: codedeploy
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#  bucket: "abhilash-nexthoughts"
#  key: target.zip
#  bundle_type:  zip
#  application: linkshare
#  deployment_group: nexthoughts
#  region: "us-east-1"
#  on:
#    branch: master